# Generated by Django 5.0 on 2023-12-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-title'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
